/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tonyshark_store_Store */

#ifndef _Included_com_tonyshark_store_Store
#define _Included_com_tonyshark_store_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tonyshark_store_Store
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tonyshark_store_Store_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getBoolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tonyshark_store_Store_getBoolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setBoolean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getByte
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_com_tonyshark_store_Store_getByte
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setByte
 * Signature: (Ljava/lang/String;B)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setByte
  (JNIEnv *, jobject, jstring, jbyte);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getChar
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_tonyshark_store_Store_getChar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setChar
 * Signature: (Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setChar
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_tonyshark_store_Store_getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setDouble
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setDouble
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getFloat
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_tonyshark_store_Store_getFloat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setFloat
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setFloat
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tonyshark_store_Store_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getLong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_tonyshark_store_Store_getLong
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setLong
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setLong
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getShort
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_tonyshark_store_Store_getShort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setShort
 * Signature: (Ljava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setShort
  (JNIEnv *, jobject, jstring, jshort);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tonyshark_store_Store_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getColor
 * Signature: (Ljava/lang/String;)Lcom/tonyshark/store/Color;
 */
JNIEXPORT jobject JNICALL Java_com_tonyshark_store_Store_getColor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setColor
 * Signature: (Ljava/lang/String;Lcom/tonyshark/store/Color;)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setColor
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getBooleanArray
 * Signature: (Ljava/lang/String;)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_tonyshark_store_Store_getBooleanArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setBooleanArray
 * Signature: (Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setBooleanArray
  (JNIEnv *, jobject, jstring, jbooleanArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getByteArray
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tonyshark_store_Store_getByteArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setByteArray
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setByteArray
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getCharArray
 * Signature: (Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_tonyshark_store_Store_getCharArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setCharArray
 * Signature: (Ljava/lang/String;[C)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setCharArray
  (JNIEnv *, jobject, jstring, jcharArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getDoubleArray
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_tonyshark_store_Store_getDoubleArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setDoubleArray
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setDoubleArray
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getFloatArray
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_tonyshark_store_Store_getFloatArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setFloatArray
 * Signature: (Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setFloatArray
  (JNIEnv *, jobject, jstring, jfloatArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getIntegerArray
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tonyshark_store_Store_getIntegerArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setIntegerArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setIntegerArray
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getLongArray
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_tonyshark_store_Store_getLongArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setLongArray
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setLongArray
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getShortArray
 * Signature: (Ljava/lang/String;)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_tonyshark_store_Store_getShortArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setShortArray
 * Signature: (Ljava/lang/String;[S)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setShortArray
  (JNIEnv *, jobject, jstring, jshortArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getStringArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tonyshark_store_Store_getStringArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setStringArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setStringArray
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    getColorArray
 * Signature: (Ljava/lang/String;)[Lcom/tonyshark/store/Color;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tonyshark_store_Store_getColorArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    setColorArray
 * Signature: (Ljava/lang/String;[Lcom/tonyshark/store/Color;)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_setColorArray
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    startWatcher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tonyshark_store_Store_startWatcher
  (JNIEnv *, jobject);

/*
 * Class:     com_tonyshark_store_Store
 * Method:    stopWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tonyshark_store_Store_stopWatcher
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
